import React from 'react';
import Head from 'next/head'
import Schedule from "../components/Schedule"
import axios from 'axios'
import SmallSchedule from "../components/SmallSchedule";
import useGames from "./api/swr/useGames";
import Loader from "../components/Loader";
const Index = () => {
    const { games, isValidating} =  useGames()
    if( isValidating){
        return (
            <div className={`flex h-screen w-screen bg-white items-center justify-center`}>
                <span><Loader/></span>
            </div>
        )
    }
    return (
        <div>
            <Head>
                <title>Bavel JO17-4</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={`hidden lg:flex md:items-center md:justify-center h-screen w-full`}>
               <Schedule  games={games} />
            </div>
            <div className={`h-screen w-full lg:hidden`}>
                <SmallSchedule  games={games} />
            </div>

        </div>
    );
};

export default Index;
